### ISSUE TITLE
No such file or directory: 'pope_coco/coco_ground_truth_segmentation.json'

### ISSUE THREAD

**Issue by XueJiang16** [BillChan226/contrast_decoding_LVLMs#1]
Hi, when I run  pope_eval.py, it seems that there is no such file. I think this may be a generated file by yourself. Could please provide it to me?

Thanks a lot!

**Comment by BillChan226** [comment]
Hi,

Thanks for reporting this issue! We have used the `coco_ground_truth_segmentation.json` file from the original pope benchmark repository, if this is the missing file you referred to. The link to the file is [here](https://github.com/RUCAIBox/POPE/blob/main/segmentation/coco_ground_truth_segmentation.json), you can download it and specify its path using the `--gt_seg_path` argument. We have also unignored the file in our [repo](https://github.com/BillChan226/HALC/blob/591282d300c9d3f54224970a435a4480b75a9ba9/pope_coco/coco_ground_truth_segmentation.json), you should be able to directly run it now.

Please let us know if this address your issue, and we will be happy to help if there are further questions!
