### ISSUE TITLE
Size mismatch for llama_proj.weight

### ISSUE THREAD

**Issue by Rainlt** [BillChan226/contrast_decoding_LVLMs#10]
Hello, I have tried to reproduce the results of Minigpt4, but got such error:

```
Initializing Model
Loading VIT
Loading VIT Done
Do not use Q-Former here.
Loading LLAMA
llama_model:  /sda/lt/model/Llama-2-7b-chat-hf
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.45it/s]
Loading LLAMA Done
Load BLIP2-LLM Checkpoint: /sda/lt/model/minigpt4-7b/pretrained_minigpt4_7b.pth
Traceback (most recent call last):
  File "/home/lt/project/HALC/run_scripts/caption_generation.py", line 257, in <module>
    model = model_cls.from_config(model_config).to(device)
  File "/home/lt/project/HALC/./minigpt4/models/mini_gpt4.py", line 517, in from_config
    msg = model.load_state_dict(ckpt['model'], strict=False)
  File "/home/lt/anaconda3/envs/halc/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MiniGPT4:
        size mismatch for llama_proj.weight: copying a param with shape torch.Size([4096, 768]) from checkpoint, the shape in current model is torch.Size([4096, 5632]).
```
The main cause may be the Q-Former. In line 80 of mini_gpt4.py，if model use Q-Former，"img_f_dim = self.Qformer.config.hidden_size", if not, img_f_dim = self.visual_encoder.num_features * 4.

I found that the "eval_configs/minigpt4_eval.yaml" will be merged with "configs/models/minigpt4_llama2.yaml", where "has_qformer: False". Because the "model_type" in "eval_configs/minigpt4_eval.yaml" is "pretrain_llama2".

If I change  "pretrain_llama2" to "pretrain_vicuna0", it can run well. 

Further more, How can I use minigpt4-llama2 as the backbone? I have tried to simply modify the "MODEL_EVAL_CONFIG_PATH" in "run_scripts/caption_generation.py", but get strange outputs.

The "[MiniGPT-4 7B pretrained weights](https://drive.google.com/file/d/1RY9jV0dyqLX-o38LrumkKRh6Jtaop58R/view?usp=sharing)" and “[MiniGPT-4 7B pretrained weights for LlaMA-2](https://drive.google.com/file/d/1RY9jV0dyqLX-o38LrumkKRh6Jtaop58R/view?usp=sharing)” seems to be the same one. Could there be anything wrong with this?

**Comment by XixiLiu95** [comment]
Hi,

I fixed it by changing Line3 in minigpt4_eval.yaml to  model_type: pretrain_vicuna0

**Comment by BillChan226** [comment]
Thanks!!
