### ISSUE TITLE
作者大大你好，为啥在HALC评测的LLava-1.5的Ci和CS值都差不多是OPERA论文里面的两倍呢，在评测时，有什么不一样的地方嘛

### ISSUE THREAD

**Issue by alex1243423** [BillChan226/contrast_decoding_LVLMs#19]

**Comment by BillChan226** [comment]
Hi, thanks for your interest in HALC!

Could you please share the output captions produced by HALC and OPERA and the hyperparameters such as dataset, seed, etc, to better understand the issue?

The hyperparameters defaulted in the repo are optimized for more smooth and efficient inference. To obtain better results, you are suggested to follow the hyperparameter outlined in the Appendix of the paper, and set `skip_rate` [here](https://github.com/BillChan226/HALC/blob/c757ced4f1f26d992e6e7200a44d3b899bb000af/decoder_zoo/HALC/context_density/halc.py#L79) to`0` to apply HALC on each targeted token to obtain better performance regarding hallucination.

Meanwhile, we would suggest you use  the `--debugger 1` mode to print out all metadata during HALC decoding to understand how it handles hallucinating tokens. For example,

```
python run_scripts/caption_generation.py --debugger 1
```

Please let us know if you have further question!!

**Comment by alex1243423** [comment]
谢谢作者大大嘞，我没有跑任何的复现，只是好奇这两个为啥有一定的差距，那我理解了，是选择的样本不一样，所以计算出来才会有差距。

**Comment by BillChan226** [comment]
Glad that your concerns are addressed:) 

Please reach out if you have further questions! Thank you!
