### ISSUE TITLE
No minigpt4/configs/models/minigpt4_vicuna0.yaml

### ISSUE THREAD

**Issue by fmmarkmq** [BillChan226/contrast_decoding_LVLMs#3]
Awesome project! But I found that minigpt4/configs/models/minigpt4_vicuna0.yaml does not exist. Please fix it. Thank you!

**Comment by BillChan226** [comment]
Hi, thanks for your interest in our project. We have added the configuration for minigpt4_vicuna0 [here](minigpt4/configs/models/minigpt4_vicuna0.yaml) under your request. Thanks for helping to improve our repo:)
