### ISSUE TITLE
How to calculate the OPOPE score?

### ISSUE THREAD

**Issue by zhaoshitian** [BillChan226/contrast_decoding_LVLMs#5]
How to calculate the OPOPE score?

**Comment by BillChan226** [comment]
Hi, thanks for your interest in HALC! We have unified the evaluation in `eval/batch_eval.py` script. You can simply run it via:
`python eval/batch_eval.py -c [PATH_TO_CAPTION_FOLDER_DIR] --evaluator pope --pope_type [random/popular/adversarial]` 
You can check the detailed calculation in `eval/opope_eval.py`. Please let me know if there's further questions! Thanks:)
