### ISSUE TITLE
您好！我在运行您的代码时出现了环境问题

### ISSUE THREAD

**Issue by qppwdd0324** [BillChan226/contrast_decoding_LVLMs#6]
请问您的spacy/pydantic/typing extensions的版本号分别是多少？感谢您！

**Comment by BillChan226** [comment]
Hi, thanks for your interest in HALC! Here is the package version in our environment:
```
spacy                     3.7.2
spacy-legacy              3.0.12
spacy-loggers             1.0.5
pydantic                  2.5.3
pydantic_core             2.14.6
typing_extensions         4.8.0
```
If you need further help with the environment setup, please don't hesitate to let me know!

**Comment by qppwdd0324** [comment]
我在评估chair时遇到了困难，请问 pattern的版本号是多少

**Comment by pandawynn** [comment]
> 我在评估chair时遇到了困难，请问 pattern的版本号是多少

hi, is this issue resolved? I’m encountering the same problem.

**Comment by BillChan226** [comment]
> 我在评估chair时遇到了困难，请问 pattern的版本号是多少

Hi, you can try to install pattern using `conda install -c conda-forge pattern`

**Comment by BillChan226** [comment]
> Referen

Hi, I wasn't able to track back to the pattern version I used before, but it could be fixed using `Hi, you can try to install pattern using` in most of the cases.

**Comment by pandawynn** [comment]
> 我在评估chair时遇到了困难，请问 pattern的版本号是多少

 The `pattern==3.6` will work in my experiment.

**Comment by pspdada** [comment]
> Hi, thanks for your interest in HALC! Here is the package version in our environment:
> 
> ```
> spacy                     3.7.2
> spacy-legacy              3.0.12
> spacy-loggers             1.0.5
> pydantic                  2.5.3
> pydantic_core             2.14.6
> typing_extensions         4.8.0
> ```
> 
> If you need further help with the environment setup, please don't hesitate to let me know!

Hi, I found the `- spacy-model-en_core_web_sm=3.5.0` in the `dependencies` of doc [HALC](https://github.com/BillChan226/HALC/tree/OH_zoo)
/environment.yml, which means the version of spacy might be `3.5.0`. Which one is the right one?
