### ISSUE TITLE
ERROR in evaluation CHAIR.

### ISSUE THREAD

**Issue by ZaneKan0** [BillChan226/contrast_decoding_LVLMs#8]
Thanks for your great work! But I got error when I ran evaluation of CHAIR.

I used 'run_scripts/caption_generation.py' to get a json file in the following format. 
<img width="879" alt="image" src="https://github.com/BillChan226/HALC/assets/162621327/1f6a0d1f-251a-4f33-b8aa-8640951e8f6d">

When I used 'eval/eval_hallucination.py' to test it, I got the following error. 
<img width="483" alt="image" src="https://github.com/BillChan226/HALC/assets/162621327/1c93e113-9096-4ee7-9256-79f59ae901f0">

How can I solve it? Thanks a lot!

**Comment by XixiLiu95** [comment]
Hi,

You might need to firstly generate the corresponding _chair.json file by doing 
 ``` bash
python eval/caption_to_chair.py -c [PATH_TO_CAPTION_FOLDER_DIR] 
```
The path of the generated file should be passed to ``` --chair_input_path ```.  By doing this, it should work. However, I did not obtain similar results to the ones reported. Let me know if that works for you! If yes, did you get similar results? Thanks!
